[package]
name = "raspi-img-builder"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
fatfs = "0.3.3"
fscommon = "0.1.0"
mbrman = "0.3.1"
structopt = "0.3.5"
walkdir = "2.3.1"
