[package]
name = "hello-world"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
nametbd-stdout-interface = { path = "../../interfaces/stdout" }
