---
kind: Service
apiVersion: v1
metadata:
  name: passive-node
spec:
  type: LoadBalancer
  selector:
    app: passive-node
  ports:
    - name: libp2p
      protocol: TCP
      port: 30333
      targetPort: 30333
---
apiVersion: v1
kind: Secret
metadata:
  name: p2p-loader-private-key
type: Opaque
data:
  private_key: cCzPG7dMwMIOJ25gBUFgC1cooYQmiZ54HKfzH2W8AmQ=   # TODO: that's not exactly "secret"
---
apiVersion: apps/v1
kind: Deployment # TODO: shouldn't that be a StatefulSet?
metadata:
  name: passive-node
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: passive-node
  template:
    metadata:
      labels:
        app: passive-node
    spec:
      containers:
      - name: passive-node
        # Note: `<TAG>` is replaced by a script before deployment
        image: tomaka/redshirt-passive-node:<TAG>
        env:
        - name: RUST_LOG
          value: p2p_loader=TRACE
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: p2p-loader-private-key # TODO: we need one key per node :facepalm:
              key: private_key
        ports:
        - containerPort: 30333
          protocol: TCP
