---
kind: Service
apiVersion: v1
metadata:
  name: passive-node
spec:
  type: NodePort
  ports:
  - port: 30333
    name: p2p
    nodePort: 30333
    protocol: TCP
  selector:
    app: passive-node
  sessionAffinity: None
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Secret
metadata:
  name: p2p-loader-private-key
type: Opaque
data:
  private_key: Y0N6UEc3ZE13TUlPSjI1Z0JVRmdDMWNvb1lRbWlaNTRIS2Z6SDJXOEFtUT0=   # TODO: that's not exactly "secret"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: passive-node
spec:
  serviceName: passive-node
  replicas: 1
  selector:
    matchLabels:
      app: passive-node
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: passive-node
    spec:
      affinity:
        # Force a maximum of one container per node, otherwise the ports will conflict
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - passive-node
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: passive-node
        # Note: `<TAG>` is replaced by a script before deployment
        image: tomaka/redshirt-passive-node:<TAG>
        # TODO: shouldn't be necessary, for some reason fails if we don't do that
        command: ["/usr/local/bin/passive-node"]
        args: ["--git-watch", "https://github.com/tomaka/redshirt-packages"]
        env:
        - name: RUST_LOG
          value: p2p_loader=TRACE
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: p2p-loader-private-key # TODO: we need one key per node :facepalm:
              key: private_key
        ports:
        - containerPort: 30333
          protocol: TCP
          name: p2p
