[workspace]
members = [
    "ipfs",
    "vulkan-triangle",
    "wasm-timer",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'

[patch.crates-io]
wasm-timer = { path = "./wasm-timer" }
