[workspace]
members = [
    "hello-world",
    "http-server",
    "ipfs",
    "vulkan-triangle",
    "time",
    "wasm-timer",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'

[patch.crates-io]
time = { path = "./time" }
wasm-timer = { path = "./wasm-timer" }
