[workspace]
members = [
    "hello-world",
    "http-server",
    "log-to-kernel",
    "ne2000",
    "p2p-loader",
    "rpi-framebuffer",
    "stub",
    "third-party/time",
    "third-party/wasm-timer",
    "x86-pci",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'

[patch.crates-io]
ring = { git = "https://github.com/nhynes/ring", branch = "wasi" }
time = { path = "./third-party/time" }
wasm-timer = { path = "./third-party/wasm-timer" }
