[workspace]
members = [
    "arm-stdout",
    "hello-world",
    "http-server",
    "p2p-loader",
    "third-party/time",
    "third-party/wasm-timer",
    "vulkan-triangle",
    "x86-stdout"
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'

[patch.crates-io]
time = { path = "./third-party/time" }
wasm-timer = { path = "./third-party/wasm-timer" }
