[workspace]
members = [
    "core",
    "core-proc-macros",
    "kernel/cli",
    "kernel/hosted-log",
    "kernel/hosted-tcp",
    "kernel/hosted-time",
    "kernel/standalone",
    "interfaces/hardware",
    "interfaces/interface",
    "interfaces/loader",
    "interfaces/log",
    "interfaces/pci",
    "interfaces/random",
    "interfaces/syscalls",
    "interfaces/threads",
    "interfaces/tcp",
    "interfaces/time",
    "interfaces/vulkan",
    "interfaces/window",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
