[workspace]
members = [
    "core",
    "hosted/cli",
    "hosted/kernel",
    "hosted/tcp",
    "hosted/time",
    "hosted/wasi",
    "interfaces/interface",
    "interfaces/loader",
    "interfaces/syscalls",
    "interfaces/threads",
    "interfaces/tcp",
    "interfaces/time",
    "interfaces/vulkan",
    "interfaces/window",
    "standalone",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
