[workspace]
members = [
    "core",
    "kernel/cli",
    "kernel/hosted-tcp",
    "kernel/hosted-time",
    "kernel/hosted-wasi",
    "kernel/standalone",
    "kernel/x86-stdout",
    "interfaces/interface",
    "interfaces/loader",
    "interfaces/stdout",
    "interfaces/syscalls",
    "interfaces/threads",
    "interfaces/tcp",
    "interfaces/time",
    "interfaces/vulkan",
    "interfaces/window",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
