[package]
name = "x86-stdout"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
nametbd-hardware-interface = { path = "../../interfaces/hardware", default-features = false }
nametbd-interface-interface = { path = "../../interfaces/interface" }
nametbd-stdout-interface = { path = "../../interfaces/stdout" }
nametbd-syscalls-interface = { path = "../../interfaces/syscalls" }
parity-scale-codec = { version = "1.0.5", default-features = false }
