[package]
name = "ipfs"       # TODO: rename; this isn't actually ipfs
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = { version = "0.3.1", features = ["compat", "io-compat"] }
futures01 = { package = "futures", version = "0.1" }
libp2p-core = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-kad = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-mplex = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
#libp2p-secio = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-plaintext = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-swarm = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
log = "0.4"
nametbd-interface-interface = { path = "../../interfaces/interface" }
nametbd-loader-interface = { path = "../../interfaces/loader" }
nametbd-syscalls-interface = { path = "../../interfaces/syscalls" }
nametbd-tcp-interface = { path = "../../interfaces/tcp" }
parity-scale-codec = "1.0.5"
