[package]
name = "stub"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
redshirt-syscalls-interface = { path = "../../interfaces/syscalls" }
wee_alloc = "0.4.5"
