[package]
name = "redshirt-cli-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false
default-run = "redshirt-cli-kernel"

[dependencies]
async-std = "1.3"
futures = "0.3.1"
redshirt-core = { path = "../../core" }
redshirt-stdout-interface = { path = "../../interfaces/stdout" }
redshirt-tcp-hosted = { path = "../hosted-tcp" }
redshirt-tcp-interface = { path = "../../interfaces/tcp" }
redshirt-time-hosted = { path = "../hosted-time" }
redshirt-time-interface = { path = "../../interfaces/time" }
redshirt-wasi-hosted = { path = "../hosted-wasi" }
parity-scale-codec = "1.0.5"
wasi = "0.7.0"

[build-dependencies]
walkdir = "2.2.9"
