[package]
name = "redshirt-standalone-tester"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
structopt = "0.3.5"
tempdir = "0.3.7"
