[package]
name = "getrandom"
version = "0.1.14"
edition = "2018"
authors = ["The Rand Project Developers"]
license = "MIT OR Apache-2.0"
description = "A small cross-platform library for retrieving random data from system source"
documentation = "https://docs.rs/getrandom"
repository = "https://github.com/rust-random/getrandom"
categories = ["os", "no-std"]
exclude = ["utils/*", ".*", "appveyor.yml"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Note: we use the git version because the crates.io version lead to a recursive dependency
actual-getrandom = { package = "getrandom", git = "https://github.com/rust-random/getrandom" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
redshirt-random-interface = { path = "../../../interfaces/random" }
redshirt-syscalls = { path = "../../../interfaces/syscalls" }

[features]
std = []
dummy = []
rustc-dep-of-std = []
test-in-browser = []
