[package]
name = "p2p-loader"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3"
libp2p-core = { git = "https://github.com/tomaka/libp2p-rs", branch = "stable-fut-wasi" }
libp2p-kad = { git = "https://github.com/tomaka/libp2p-rs", branch = "stable-fut-wasi" }
libp2p-mplex = { git = "https://github.com/tomaka/libp2p-rs", branch = "stable-fut-wasi" }
#libp2p-secio = { git = "https://github.com/tomaka/libp2p-rs", branch = "stable-fut-wasi" }
libp2p-plaintext = { git = "https://github.com/tomaka/libp2p-rs", branch = "stable-fut-wasi" }
libp2p-swarm = { git = "https://github.com/tomaka/libp2p-rs", branch = "stable-fut-wasi" }
log = "0.4"
nametbd-interface-interface = { path = "../../interfaces/interface" }
nametbd-loader-interface = { path = "../../interfaces/loader" }
nametbd-syscalls-interface = { path = "../../interfaces/syscalls" }
nametbd-tcp-interface = { path = "../../interfaces/tcp" }
nametbd-time-interface = { path = "../../interfaces/time" }
parity-scale-codec = "1.0.5"
