[package]
name = "redshirt-wasi-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
byteorder = { version = "1.3.2", default-features = false }
hashbrown = { version = "0.6.0", default-features = false }
redshirt-core = { path = "../../core", default-features = false }
redshirt-random-interface = { path = "../../interfaces/random", default-features = false }
redshirt-stdout-interface = { path = "../../interfaces/stdout", default-features = false }
redshirt-syscalls-interface = { path = "../../interfaces/syscalls", default-features = false }
redshirt-time-interface = { path = "../../interfaces/time", default-features = false }
parity-scale-codec = { version = "1.1.0", default-features = false }
