[package]
name = "nametbd-wasi-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
byteorder = { version = "1.3.2", default-features = false }
hashbrown = { version = "0.6.0", default-features = false }
nametbd-core = { path = "../../core", default-features = false }
nametbd-random-interface = { path = "../../interfaces/random", default-features = false }
nametbd-stdout-interface = { path = "../../interfaces/stdout", default-features = false }
nametbd-time-interface = { path = "../../interfaces/time", default-features = false }
parity-scale-codec = { version = "1.1.0", default-features = false }

# TODO: remove
wasmi = { git = "https://github.com/tomaka/wasmi", branch = "no-std", default-features = false, features = ["core"] }
