[package]
name = "log-to-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-kernel-log-interface = { path = "../../interfaces/kernel-log" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
