[package]
name = "redshirt-tcp-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
async-std = "1.6"
atomic = "0.5.0"
fnv = "1.0"
futures = "0.3.8"
parking_lot = "0.11.1"
redshirt-core = { path = "../../core" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-tcp-interface = { path = "../../interfaces/tcp" }
parity-scale-codec = "1.3.5"
rand = "0.7"
