[package]
name = "nametbd-tcp-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
async-std = "1.0"
fnv = "1.0"
futures = "0.3.1"
nametbd-tcp-interface = { path = "../../interfaces/tcp" }
parity-scale-codec = "1.0.5"
rand = "0.7"
