[package]
name = "vulkan-triangle"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
# TODO: upstream the changes
syscalls = { path = "../../interfaces/syscalls" }
vulkano = { git = "https://github.com/tomaka/vulkano", branch = "wasm" }
vulkano-shaders = { git = "https://github.com/tomaka/vulkano", branch = "wasm" }
vulkan = { path = "../../interfaces/vulkan" }
vk-sys = { git = "https://github.com/tomaka/vulkano", branch = "wasm" }
window = { path = "../../interfaces/window" }
