[package]
name = "vulkan-triangle"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
nametbd-syscalls-interface = { path = "../../interfaces/syscalls" }
nametbd-vulkan-interface = { path = "../../interfaces/vulkan" }
nametbd-window-interface = { path = "../../interfaces/window" }
# TODO: upstream the changes
vulkano = { git = "https://github.com/tomaka/vulkano", branch = "wasm" }
vulkano-shaders = { git = "https://github.com/tomaka/vulkano", branch = "wasm" }
vk-sys = { git = "https://github.com/tomaka/vulkano", branch = "wasm" }
