[package]
name = "usb-controller-driver"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
derive_more = "0.99.5"
futures = "0.3"
lazy_static = "1"
log = "0.4"
redshirt-hardware-interface = { path = "../../interfaces/hardware" }
redshirt-pci-interface = { path = "../../interfaces/pci" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
parity-scale-codec = { version = "1.0.5", default-features = false }
