[package]
name = "http-server"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.1"
hyper = { version = "0.13.0-alpha.4", default-features = false }
redshirt-stdout-interface = { path = "../../interfaces/stdout" }
redshirt-syscalls-interface = { path = "../../interfaces/syscalls" }
redshirt-tcp-interface = { path = "../../interfaces/tcp" }
tokio-executor = "0.2.0-alpha.6"
