[package]
name = "vga-vbe"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
derive_more = "0.99.8"
fnv = { git = "https://github.com/dflemstr/rust-fnv", default-features = false }    # TODO: https://github.com/servo/rust-fnv/pull/22
hashbrown = { version = "0.7.1", default-features = false }
iced-x86 = { version = "1.2.0", default-features = false, features = ["decoder", "instr_info", "std"] }
lazy_static = "1"
log = "0.4"
redshirt-hardware-interface = { path = "../../interfaces/hardware" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-kernel-log-interface = { path = "../../interfaces/kernel-log" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-pci-interface = { path = "../../interfaces/pci" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-video-output-interface = { path = "../../interfaces/video-output" }

[dev-dependencies]
futures = "0.3.7"
