[package]
name = "nametbd-time-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.0"
futures-timer = "2.0"
nametbd-time-interface = { path = "../../interfaces/time" }
parity-scale-codec = "1.1.0"
lazy_static = "1.4"
