[package]
name = "redshirt-standalone-builder"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
fatfs = "0.3.3"
fscommon = "0.1.0"
cargo_metadata = "0.9"
mbrman = { git = "https://github.com/cecton/mbrman" }    # TODO: waiting for a publication
serde_json = "1.0.48"
structopt = "0.3.11"
tempdir = "0.3.7"
thiserror = "1.0"
walkdir = "2.3.1"
