[package]
name = "redshirt-standalone-builder"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
fatfs = "0.3.3"
fscommon = "0.1.0"
cargo_metadata = "0.12"
mbrman = "0.3.2"
serde_json = "1.0.48"
structopt = "0.3.20"
tempdir = "0.3.7"
thiserror = "1.0"
walkdir = "2.3.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.test.package."*"]
opt-level = 3

