[package]
name = "x86-pci"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
hashbrown = "0.6.3"
lazy_static = "1"
nametbd-hardware-interface = { path = "../../interfaces/hardware" }
nametbd-interface-interface = { path = "../../interfaces/interface" }
nametbd-pci-interface = { path = "../../interfaces/pci" }
nametbd-stdout-interface = { path = "../../interfaces/stdout" }
nametbd-syscalls-interface = { path = "../../interfaces/syscalls" }
parity-scale-codec = { version = "1.0.5", default-features = false }

[build-dependencies]
regex = "1.3.1"
