[package]
name = "ne2000"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
etherparse = "0.9.0"    # TODO: temporary for debugging; remove
futures = "0.3.1"
redshirt-hardware-interface = { path = "../../interfaces/hardware" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-network-interface = { path = "../../interfaces/network" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-pci-interface = { path = "../../interfaces/pci" }
redshirt-random-interface = { path = "../../interfaces/random" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-time-interface = { path = "../../interfaces/time" }
smallvec = "1.0.0"
