[package]
name = "compositor"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.9"
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-time-interface = { path = "../../interfaces/time" }
redshirt-video-output-interface = { path = "../../interfaces/video-output" }
