[package]
name = "redshirt-standalone-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
compiler_builtins = { version = "0.1.23", features = ["mem"] }
# TODO: https://github.com/rust-lang/futures-rs/pull/2007
futures = { git = "https://github.com/tomaka/futures-rs", branch = "const-new-atomic-waker", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.6.3", default-features = false }
lazy_static = "1.4"
libm = "0.2.1"
linked_list_allocator = "0.6.4"
redshirt-core = { path = "../../core" }
redshirt-interface-interface = { path = "../../interfaces/interface", default-features = false }
redshirt-hardware-interface = { path = "../../interfaces/hardware", default-features = false }
redshirt-stdout-interface = { path = "../../interfaces/stdout", default-features = false }
redshirt-syscalls-interface = { path = "../../interfaces/syscalls", default-features = false }
spin = "0.5.2"

[build-dependencies]
cc = "1.0"
walkdir = "2.2.9"

[target.'cfg(target_arch = "x86_64")'.dependencies]
acpi = "0.4.0"
multiboot2 = "0.8.1"
x86_64 = "0.8.2"
