[package]
name = "redshirt-standalone-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
blake3 = { version = "0.2.2", default-features = false }
crossbeam-queue = { version = "0.2.1", default-features = false, features = ["alloc"] }
futures = { version = "0.3.2", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.7.1", default-features = false }
lazy_static = "1.4"
libm = "0.2.1"
linked_list_allocator = { version = "0.8.1", features = ["alloc_ref"] }
nohash-hasher = { version = "0.2.0", default-features = false }
rand_chacha = { version = "0.2.1", default-features = false }
rand_core = { version = "0.5.1", default-features = false }
# TODO: needs https://github.com/rust-random/rngs/pull/5
rand_jitter = { git = "https://github.com/tomaka/rngs", branch = "new-with-timer-less-cumbersome", default-features = false }
redshirt-core = { path = "../../core", features = ["nightly"] }
redshirt-interface-interface = { path = "../../interfaces/interface", default-features = false }
redshirt-hardware-interface = { path = "../../interfaces/hardware", default-features = false }
redshirt-random-interface = { path = "../../interfaces/random", default-features = false }
redshirt-log-interface = { path = "../../interfaces/log", default-features = false }
redshirt-syscalls = { path = "../../interfaces/syscalls", default-features = false }
redshirt-time-interface = { path = "../../interfaces/time", default-features = false }
rlibc = "1.0.0"
smallvec = { version = "1.2.0", default-features = false }
spinning_top = "0.1.0"

[build-dependencies]
cc = "1.0"
walkdir = "2.2.9"

[target.'cfg(target_arch = "x86_64")'.dependencies]
acpi = { git = "https://github.com/tomaka/acpi", branch = "optional-local-nmi" }
multiboot2 = "0.8.1"
x86_64 = "0.8.2"
