[package]
name = "nametbd-standalone-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = { version = "0.3.1", default-features = false }
nametbd-core = { path = "../../core" }
nametbd-stdout-interface = { path = "../../interfaces/stdout" }
nametbd-x86-stdout = { path = "../x86-stdout" }
parity-scale-codec = { version = "1.0.5", default-features = false }
slab_allocator = "0.3.5"
