[package]
name = "nametbd-standalone-kernel"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
compiler_builtins = { version = "0.1.23", features = ["mem"] }
futures = { version = "0.3.1", default-features = false }
libm = "0.2.1"
linked_list_allocator = "0.6.4"
nametbd-core = { path = "../../core" }
nametbd-hardware = { path = "../hardware" }
nametbd-hardware-interface = { path = "../../interfaces/hardware" }
nametbd-wasi-hosted = { path = "../hosted-wasi" }
parity-scale-codec = { version = "1.0.5", default-features = false }

[build-dependencies]
cc = "1.0"
walkdir = "2.2.9"

[target.'cfg(target_arch = "x86_64")'.dependencies]
multiboot2 = "0.8.1"
x86 = "0.28.0"
