[package]
name = "p2p-loader"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[features]
default = []
git = ["git2", "notify", "openssl-sys"]

[dependencies]
base64 = { version = "0.13.0", default-features = false, features = ["alloc"] }
blake3 = { version = "0.3.8", default-features = false }
bs58 = "0.4.0"
futures = "0.3"
git2 = { version = "0.13.21", optional = true }
libp2p = { version = "0.23.0", default-features = false, features = ["kad", "noise", "yamux"] }
log = "0.4"
notify = { version = "4.0.17", optional = true }
# openssl-sys is not used directly, but we want to pass the "vendored" feature
openssl-sys = { version = "0.9.66", features = ["vendored"], optional = true }
parity-scale-codec = "2.2.0"
structopt = "0.3.22"
tempdir = "0.3.7"
walkdir = "2.3.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.8.3"
libp2p-tcp = { version = "0.20.0", default-features = false, features = ["async-std"] }
# TODO: use the version below once cargo has fixed the associated bug
#libp2p = { version = "0.21.1", default-features = false, features = ["tcp"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-loader-interface = { path = "../../interfaces/loader" }
redshirt-log-interface = { path = "../../interfaces/log" }
redshirt-syscalls = { path = "../../interfaces/syscalls" }
redshirt-tcp-interface = { path = "../../interfaces/tcp" }
redshirt-time-interface = { path = "../../interfaces/time" }
