name: Continuous integration

on:
  pull_request:
  push:
    branches:    
      - master

jobs:
  build-modules:
    name: Build WASM modules
    runs-on: ubuntu-latest
    container:
      image: rust
      env:
        CC: clang-9
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-wasi
        override: true
    - name: Install a recent version of clang
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y clang-9
    - name: Install CMake
      run: apt-get install -y cmake
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('modules/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ hashFiles('modules/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: modules/target
        key: cargo-build-target-${{ hashFiles('modules/Cargo.lock') }}
    - name: Build modules
      run: cargo build --manifest-path ./modules/Cargo.toml --workspace --exclude stub --locked --verbose --release --target=wasm32-wasi
    - name: Upload WASM modules
      uses: actions/upload-artifact@v1
      with:
        name: wasm-modules
        path: modules/target/wasm32-wasi/release

  build-hosted:
    name: Build hosted kernel
    needs: build-modules
    runs-on: ubuntu-latest
    container:
      image: rust
      env:
        CC: clang-9
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-03-22
        target: wasm32-wasi
        override: true
    - name: Install a recent version of clang
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y clang-9
    - name: Download WASM modules
      uses: actions/download-artifact@v1
      with:
        name: wasm-modules
        path: modules/target/wasm32-wasi/release
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: cargo build --workspace --exclude redshirt-standalone-kernel --exclude redshirt-core-proc-macros --locked --verbose
    - name: Run tests
      run: cargo test --workspace --exclude redshirt-standalone-kernel --exclude redshirt-core-proc-macros --locked --verbose

  build-standalone:
    name: Build standalone kernel
    needs: build-modules
    runs-on: ubuntu-latest
    container:
      image: rust
      env:
        CC: clang-9
    strategy:
      matrix:
        #target: [x86_64-multiboot2, arm-rpi2]  # TODO: not implemented
        target: [x86_64-multiboot2]
    steps:
    - uses: actions/checkout@v1
    - name: Download WASM modules
      uses: actions/download-artifact@v1
      with:
        name: wasm-modules
        path: modules/target/wasm32-wasi/release
    - name: Install required packages
      run: |
        apt-get update
        apt-get install -y lld libisoburn1 xorriso grub-pc-bin
    - name: Install a recent version of clang
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y clang-9
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}-standalone
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-03-22
        target: wasm32-wasi
        override: true
    - name: Install rust-src
      run: rustup component add rust-src
    - name: Build kernel
      run: cargo run --manifest-path=./kernel/standalone-builder/Cargo.toml -- build-image --target ${{ matrix.target }} --device-type cdrom --out image
    - name: Upload generated kernel
      uses: actions/upload-artifact@master
      with:
        name: kernel-${{ matrix.target }}
        path: image

  check-passive-node:
    name: Check p2p passive node
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('modules/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ hashFiles('modules/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: modules/target
        key: passive-node-check-target-${{ hashFiles('modules/Cargo.lock') }}
    - name: Check peer-to-peer passive node
      run: cargo check --manifest-path ./modules/Cargo.toml --package p2p-loader --bin passive-node --locked --verbose --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Run cargo fmt on root workspace
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo fmt on modules workspace
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=modules/Cargo.toml -- --check
      - name: Run cargo fmt on standalone tester workspace
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=kernel/standalone-builder/Cargo.toml -- --check

  intra-doc-links:
    name: Check intra-doc links
    runs-on: ubuntu-latest
    container:
      image: rust
      env:
        CC: clang-9
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-03-22
          target: wasm32-wasi
          override: true
      - name: Install a recent version of clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" >> /etc/apt/sources.list
          apt-get update
          apt-get install -y clang-9
      - name: Check core intra-doc links
        run: RUSTDOCFLAGS="--deny intra_doc_link_resolution_failure" cargo doc --verbose --workspace --no-deps --document-private-items
      - name: Check modules intra-doc links
        run: RUSTDOCFLAGS="--deny intra_doc_link_resolution_failure" cargo doc --verbose --manifest-path modules/Cargo.toml --workspace --no-deps --document-private-items
