name: Continuous integration

on: [push, pull_request]

jobs:
  build:
    name: Build and check
    runs-on: ubuntu-latest
    container:
      image: rust
      env:
        CC: clang-9
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        # TODO: put back `nightly` after https://github.com/rust-lang/rust/issues/65335 is fixed
        toolchain: nightly-2019-09-30
        target: wasm32-wasi
        override: true
    - name: Install a recent version of Clang
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y clang-9
    - name: Install CMake
      run: apt-get install -y cmake
    - name: Install Vulkan
      run: apt-get install -y libvulkan-dev
    - name: Build
      run: cargo +nightly-2019-09-30 build --locked --verbose
    - name: Run tests
      run: cargo +nightly-2019-09-30 test --locked --verbose
  
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
